### ISSUE TITLE
[JOSE review]: List of software dependencies

### ISSUE THREAD

**Issue by arokem** [kmader/Quantitative-Big-Imaging-2018#22]
Though there are local references to dependencies in various parts of the materials (including in slides and in videos) It would be good to have a list of all the software dependencies in one place (e.g., in the README file).

**Comment by kmader** [comment]
I have added a more detailed list of software dependencies including an exact list of all packages and versions to the [wiki page](https://github.com/kmader/Quantitative-Big-Imaging-2018/wiki/Full-Package-List) and made a [Docker Hub image](https://hub.docker.com/r/kmader/qbi2018/) from the latest repo to embody any dependencies that might somehow disappear in the future
